import type { Metadata } from "next";
import "./globals.css";
import {Prompt, Karla, Roboto_Mono } from 'next/font/google'

const roboto = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto',
})
const prompt = Prompt({
  weight: '600',
  variable: '--font-prompt',
  subsets: ['latin']
})

const karla = Karla({
  subsets: ['latin'],
  variable: '--font-karla',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${roboto.variable} ${prompt.variable}  ${karla.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
